version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://authuser:supersecret@auth-db:5432/auth
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRATION=36000
    depends_on:
      - auth-db

  products-api:
    build:
      context: ./services/products-api
    container_name: products-api
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@products-db:5432/products
    depends_on:
      - products-db
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - authdata:/var/lib/postgresql/data

  products-db:
    image: postgres:15
    container_name: products-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - "5433:5432"
    volumes:
      - productsdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices_network
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    healthcheck:
      test: ["CMD", "mongo", "admin", "-u", "root", "-p", "rootpassword", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  cart-api:
    build:
      context: ./services/cart-api
      dockerfile: Dockerfile
    container_name: cart-api
    restart: always
    networks:
      - microservices_network
    ports:
      - "8002:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/cart-service
      - MONGO_USER=root
      - MONGO_PASSWORD=rootpassword
      - MONGO_DB=cart-service
      - AUTH_SERVICE_URL=http://auth-api:3010
    depends_on:
      - mongodb

networks:
  microservices_network:
    driver: bridge


volumes:
  authdata:
  productsdata:
  mongo_data: