apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: tussi-services
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: us-central1-docker.pkg.dev/tussi-466501/microservices-repo/api-gateway:REPLACE_WITH_TAG
        ports:
        - containerPort: 9000
        env:
        - name: JWT_SECRET
          value: "supersecretkey"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8000"
        - name: PRODUCTS_SERVICE_URL
          value: "http://products-service:8000"
        - name: CART_SERVICE_URL
          value: "http://cart-service:8000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: tussi-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 