apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: tussi-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "authuser"
        - name: POSTGRES_PASSWORD
          value: "supersecret"
        - name: POSTGRES_DB
          value: "auth"
        volumeMounts:
        - name: auth-db-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - authuser
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - pg_isready
              - -U
              - authuser
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: auth-db-storage
        persistentVolumeClaim:
          claimName: auth-db-pvc 