apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api
  namespace: tussi-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
      - name: cart-api
        image: us-central1-docker.pkg.dev/PROJECT_ID_REPLACE_ME/tussi-services/cart-api:v1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: "mongodb://root:$(MONGO_PASSWORD)@carts-db-service.tussi-databases:27017/cart-service?authSource=admin"
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
  namespace: tussi-services
spec:
  selector:
    app: cart-api
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-api-hpa
  namespace: tussi-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 