apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-pvc
  namespace: tussi-services
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 