apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-db
  namespace: tussi-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-db
  template:
    metadata:
      labels:
        app: products-db
    spec:
      containers:
      - name: products-db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "products"
        volumeMounts:
        - name: products-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: products-db-storage
        persistentVolumeClaim:
          claimName: products-db-pvc 